yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("404/", views.page_not_found),
    path("500/", views.server_error),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls", namespace="about")),
    path("", include("posts.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "yatube.views.page_not_found"  # noqa
handler500 = "yatube.views.server_error"  # noqa

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

yatube/templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">Технологии</a>
  </p>
  <p class="m-0 text-dark text-center ">
    Социальная сеть <span style="color:red">Ya</span>tube
  </p>
</footer>

yatube/templates/index.html
{% extends "posts/base.html" %}

{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
  <div class="container">

    {% include "menu.html" with index=True %}
    {% for post in page %}
     {% include "post_item.html" with post=post %}
    {% endfor %}

  {% include "posts/paginator.html" %}

  </div>
{% endblock %} 

yatube/templates/menu.html
{% if user.is_authenticated %}
  <div class="row">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'follow_index' %}">
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}

yatube/templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="/"><span style="color:red">Ya</span>tube</a>
  <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
    Пользователь: {{ user.username }}.
    <a class="p-2 text-dark" href="{% url 'new_post' %}">Новая запись</a>
    <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
    <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
    {% else %}
    <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
    <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
    {% endif %}
  </nav>
</nav>

yatube/templates/post_item.html
<div class="card mb-3 mt-1 shadow-sm">

  <!-- Отображение картинки -->
  {% load thumbnail %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}">
  {% endthumbnail %}
  <!-- Отображение текста поста -->
  <div class="card-body">
    <p class="card-text">
      <!-- Ссылка на автора через @ -->
      <a name="post_{{ post.id }}" href="{% url 'profile' post.author.username %}">
        <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
      </a>
      {{ post.text|linebreaksbr }}
    </p>

    <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
    {% if post.group %}
      <a class="card-link muted" href="{% url 'group_posts' post.group.slug %}">
        <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
      </a>
    {% endif %}

    <!-- Отображение ссылки на комментарии -->
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        {% if post.comments.exists %}
          <div>
            Комментариев: {{ post.comments.count }}
          </div>
        {% endif %}
        <a class="btn btn-sm btn-primary" href="{% url 'post' post.author.username post.id %}" role="button">
          Добавить комментарий
        </a>

        <!-- Ссылка на редактирование поста для автора -->
        {% if user == post.author %}
          <a class="btn btn-sm btn-info" href="{% url 'post_edit' post.author.username post.id %}" role="button">
            Редактировать
          </a>
        {% endif %}
      </div>

      <!-- Дата публикации поста -->
      <small class="text-muted">{{ post.pub_date }}</small>
    </div>
  </div>
</div>